[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
Documenter = "0.20, 0.21, 0.22, 0.23, 0.24"
DataFrames = "0.19, 0.20, 0.21"
